spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books?serverTimezone=UTC&useUnicode=false&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

    generate-ddl: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: majer.tamas.progmasters@gmail.com
    password: lazezilloymhpmxm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.example: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

cors-policies: http://localhost:4200, http://127.0.0.1:4200

